
CREATE TABLE CORREIOS_SERVICE (
	
  ID                     VARCHAR (255) NOT NULL,
  ID_CORREIOS            VARCHAR (50)  NOT NULL,
  CODE                   VARCHAR (50)  NOT NULL UNIQUE,
  DESCRIPTION            VARCHAR (50)  NOT NULL DEFAULT ('created'),
  UPDATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  POSTAL_CODE            VARCHAR (50) NOT NULL,
  
  CONSTRAINT CORREIOS_SERVICE_PK PRIMARY KEY (ID)

);