
CREATE TABLE CORREIOS_SERVICE (
	
  ID                     VARCHAR (255) NOT NULL,
  ID_CORREIOS            VARCHAR (50)  NOT NULL UNIQUE,
  CODE_CORREIOS          VARCHAR (50)  NOT NULL UNIQUE,
  DESCRIPTION_CORREIOS   VARCHAR (50)  NOT NULL DEFAULT ('created'),
  UPDATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  TYPE                    VARCHAR (50)  NOT NULL,
  
  CONSTRAINT CORREIOS_SERVICE_PK PRIMARY KEY (ID)

);